USE_CAMERA_STUB := true

# inherit from the proprietary version
#-include vendor/__MANUFACTURER__/__DEVICE__/BoardConfigVendor.mk

TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := msm7x30
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
ARCH_ARM_HAVE_TLS_REGISTER := true

# FIXME: pretty sure this is ignored
BOARD_KERNEL_CMDLINE := console=ttyDCC0 androidboot.hardware=qcomm
BOARD_KERNEL_BASE := 0x00200000
BOARD_KERNEL_PAGESIZE := 4096
BOARD_FORCE_RAMDISK_ADDRESS := 0x01300000

# FIXME: bogus size!
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x500000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x600000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0xfa00000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x3f700000
BOARD_FLASH_BLOCK_SIZE := 1

BOARD_RECOVERY_NO_FLASH := true
TARGET_USERIMAGES_USE_EXT4 := true

TARGET_PREBUILT_KERNEL := device/alcatel/cocktail/kernel
TARGET_RECOVERY_INITRC := device/alcatel/cocktail/init.recovery.rc
